services:
  workspace:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    container_name: codespace_workspace
    volumes:
      - ./:/var/www/html:cached
    depends_on:
      - mysql
    environment:
      - APACHE_RUN_USER=vscode
      - APACHE_RUN_GROUP=www-data
    # Mapeamos porta para 8080 local (evita conflito com 80 do host)
    ports:
      - "8080:80"
    tty: true

  mysql:
    image: mysql:8.0
    container_name: codespace_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: DB_PASSWORD
      MYSQL_DATABASE: DB_DATABASE
      MYSQL_USER: DB_USER
      MYSQL_PASSWORD: DB_PASSWORD
    volumes:
      - ./db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    expose:
      - "3306"

volumes:
  db_data:
